### ISSUE TITLE
Port `app-ducktape` to use musl

### ISSUE THREAD

**Issue by StefanJum** [unikraft/app-duktape#3]
Port `app-docktape` to use [musl](https://github.com/unikraft/lib-musl), the new supported unikraft glibc.

You should create the `Makefile`  and `Makefile.uk` files.
You can find more information on this on [the Unikraft website](https://unikraft.org/docs/usage/make_build/#extending-the-build).
You can find a list of the external libraries the application depends on in the [`kraft.yaml` file, under the `libraries:` section](https://github.com/unikraft/app-duktape/blob/staging/kraft.yaml#L7-L9).
You will need to replace the `newlib` dependency with `musl`.

Hackathon points: 40

**Comment by ntua-el19097** [comment]
working on this

**Comment by razvand** [comment]
Solved by #4
